'@gympass/yoga':
  - packages/yoga/**/*

'@gympass/yoga-doc':
  - packages/doc/**/*

'@gympass/yoga-icons':
  - packages/icons/**/*

'@gympass/yoga-illustrations':
  - packages/illustrations/**/*

'@gympass/yoga-tokens':
  - packages/tokens/**/*

'@gympass/yoga-common':
  - packages/common/**/*

'@gympass/yoga-system':
  - packages/system/**/*

'@gympass/yoga-labnative':
  - packages/labnative/**/*
