name: Yoga - Gympass Design System

on:
  push:
    branches:
      - master
      - alpha
      - beta

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Configure CI Git User
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GYMPASS_YOGA_DEPLOY_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
          git config --global user.email yoga@gympass.com
          git config --global user.name Yoga
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn --pure-lockfile --non-interactive
      - name: Build
        run: |
          yarn build
      - name: Publish
        run: |
            export GH_TOKEN="${{ github.token }}"
            export NPM_TOKEN="${{ secrets.YOGA_NPM_TOKEN }}"
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./.npmrc
            chmod +x ./scripts/publish
            ./scripts/publish

  doc:
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - uses: actions/checkout@v1
      - name: Configure CI Git User
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GYMPASS_YOGA_DEPLOY_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
          git checkout master
          git config --global user.email yoga@gympass.com
          git config --global user.name Yoga
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn
      - name: Build
        run: |
          CI=true
          yarn build:doc
      - name: Deploy
        run: |
          yarn deploy:doc
      - name: Slack Notify
        run: |
          SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
          node ./scripts/notify.js
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
